### ISSUE TITLE
 Cannot find module '/usr/local/lib/node_modules/homebridge-dummy-radio-switch/dist/index.js

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-dummy-radio-switch#1]
Hello Lukas,

I just tried to install your plugin. After starting the homebridge I have the following error:

<img width="1052" alt="Bildschirmfoto 2020-05-03 um 12 50 13" src="https://user-images.githubusercontent.com/27686185/80912351-a8563e80-8d3c-11ea-8364-67f13ac12578.png">

Here is my test config:

"plugins": [
"homebridge-dummy-radio-switch"
],

"accessories": [
],

"platforms": [
{
"platform": "DummyRadioSwitchPlatform",
"groups": [
{
"name": "Group 1",
"switches": [
{ "name": "G1 - Switch 1" },
{ "name": "G1 - Switch 2" }
]
},
{
"name": "Group 2",
"switches": [
{ "name": "G2 - Switch 1", "isDefaultOn": true },
{ "name": "G2 - Switch 2" },
{ "name": "G2 - Switch 3" },
{ "name": "G2 - Switch 4" }
]
}
]
}
]
}

**Comment by lukasroegner** [comment]
Sorry, as the plugin is written in TypeScript and the output is not included in the repo, it has to be installed via NPM. I published it on NPM, please install via 

```
npm install -g homebridge-dummy-radio-switch
```

**Comment by Nastras** [comment]
Plugin starts now. I'll test it now and get back to you right away :-)

**Comment by Nastras** [comment]
Test completed, it works fantastic!
Great work and thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!
