### ISSUE TITLE
Switch names don’t carry over into HomeKit

### ISSUE THREAD

**Issue by ok-jawsh** [lukasroegner/homebridge-dummy-radio-switch#10]
When naming switches inside the plug-in settings, the names do not carry over to HomeKit and therefore are not discernible between each other as they are all names the same as the Group Name in HomeKit.

**Comment by wimleers** [comment]
Noticing this too. It makes this plugin unusable.

I solved this previously in one of my Homebridge plugins: https://github.com/wimleers/homebridge-sma-home-manager/commit/a9422e05be049c4bf117c7e03ca05452079db834.

Also see https://github.com/homebridge/homebridge/issues/3281#issuecomment-1338868527.

**Comment by lukasroegner** [comment]
Should be fixed now, the latest version 0.5.1 contains a fix by @SmolSoftBoi

**Comment by ok-jawsh** [comment]
Thank you!!
