### ISSUE TITLE
[Feature Request] Timer Switch

### ISSUE THREAD

**Issue by johnlietzke** [lukasroegner/homebridge-dummy-radio-switch#3]
Could you please add a Timer to the Switch option similar to the "Dummy Switches" plugin.  The radio switch is awesome and concise.  

### https://github.com/nfarina/homebridge

`"accessories": [
        {
          "accessory": "DummySwitch",
          "name": "My Stateful Switch 1",
          "time": 5000
        }   
    ]`

**Comment by lukasroegner** [comment]
Can you explain that in detail? What should the timer do? Should it switch to off after the timer elapses?

**Comment by johnlietzke** [comment]
> After a set interval of time the switch would automatically return ﻿to the default state. 

A switches default state is off. It is turned on. After 5 minutes it returns to off.

**Comment by lukasroegner** [comment]
New option now available in 0.1.3.
