### ISSUE TITLE
Cycling through group?

### ISSUE THREAD

**Issue by mfehrenbach** [lukasroegner/homebridge-dummy-radio-switch#4]
Hi there, love the plugin—I use it to control color temperatures (maintaining a state) throughout the day.

Towards a use like that, would it be expensive to add a “cycle” option as a corollary to the “default on” flag? Thinking that you could enable this on a group, which would make the single “on” option cycle through each switch in sequence and then loop back to the beginning—turning off 1 goes to 2, turning off 2 goes to 3, 3 off to 1, etc.

I’ve done this with `Node-RED` spaghetti but it is far less performative than your radio switching! I’d try a PR here but I think the `git` and typescript is a bit beyond my chops.

**Comment by lukasroegner** [comment]
Hi @mfehrenbach,

I've implemented a feature that can be used to perform a "cycle". Here's a sample config:

```json
{
  "name": "My Group",
  "switches": [
    {
      "name": "Switch 1",
      "nextOnSwitchName": "Switch 2"
    },
    {
      "name": "Switch 2",
      "nextOnSwitchName": "Switch 3"
    },
    {
      "name": "Switch 3",
      "nextOnSwitchName": "Switch 1"
    }
  ]
}
```

**Comment by mfehrenbach** [comment]
Ah, thanks so much!
