### ISSUE TITLE
Feature Request: Custom dummy switch without radio function and with persist state

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-dummy-radio-switch#5]
Hello Lukas, I hope you are well? Even if I have told you several times I find it a pity that one hears so little of you and sees 😉

I have a request to you for this plugin.

Would it be possible to insert one or more switches that has no radio function but saves its state after a restart of the plugin? A pure dummy switch that is independent. This could be used for example as a condition to switch on and off the automations and much more.

Would be happy about an answer.

Thank you and many greetings!
Nastra

**Comment by lukasroegner** [comment]
Hi @Nastras,

Better late than never, sorry that it took such a long to time answer your feature request.
As this plugin is called "dummy radio switch", I won't implement a switch that has no radio function built in.
I would suggest taking a look at [homebridge-dummy](https://github.com/nfarina/homebridge-dummy) or [homebridge-automation-switches](https://github.com/grover/homebridge-automation-switches).
