### ISSUE TITLE
Feature Request: Timeouts per switch

### ISSUE THREAD

**Issue by BryanPatrick93** [lukasroegner/homebridge-dummy-radio-switch#6]
Timeouts per switch could be really useful. For example I’d love to be able to create a radio group that has timers setup for my fan. With timeouts for each switch in a radio group I could have 1 hour, 2 hour, and any other timer in a single group without having to have multiple regular switches for each device I want to control this way. You could even keep the timeout key that can be used now as a convenient way to make all the switches in the group have the same timeout just like it does now.

**Comment by lukasroegner** [comment]
In the new version 0.3.0, timeouts can be configured on a per-switch basis.
