### ISSUE TITLE
Timeouts per switch only works one time

### ISSUE THREAD

**Issue by Heiliger85** [lukasroegner/homebridge-dummy-radio-switch#7]
Hello, thank you for your plugin.

I have configure the plugin with 13 switches in one group. With a timeout per switch (30 sec). 
When I activate any one, the timer for this one will work, but the next switch timer doesn't work.

An example for my configuration for every switch:

"timeout": 30,
"nextOnSwitchName": "Switch2",
"isDefaultOn": false,
"name": "Switch1"

**Comment by lukasroegner** [comment]
I added this functionality in the new version 0.4.0

If a timeout switches a switch off, and that switch has a next switch configured, the timeout of the next switch will start.

**Comment by Heiliger85** [comment]
Thank you. Now it works perfectly.
